version: '3.7'

services:
  networktest:
    image: secure.cxl-terragraph.com:443/networktest:latest
    env_file:
      - {{ db_gfs_path }}/env/mysql.env
      - {{ msa_path }}/env/django.env
    restart: always
    volumes:
      - {{ msa_path }}/docker_volumes/config.json:/usr/local/nms/network_test/network_test/config.json
      - {{ msa_path }}/docker_volumes/networktest/service_config.json:/usr/local/nms/network_test/network_test/service_config.json
    ports:
      - "8000:8080"
    networks:
      - terragraph_net
    command: ["/bin/sh", "-c", "cd /usr/local/nms/network_test/network_test; until nc -z db 3306; do sleep 1; done && python manage.py migrate && python clean_up_db.py && python entry.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
  terragraph_net:
    external: true
